name: Backup all repos to gitlabwh on a schedule
on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  backup:
    if: github.repository_owner == 'deepin-community'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ".github/workflows/backup-all-repos-to-gitlabwh.bash" deepin-community ${{ secrets.BridgeToken }}